import type { Metadata } from "next";
import { Geist, Space_Mono, Geist_Mono } from "next/font/google";
import StarfieldProvider from "./components/starField-wrapper";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="bg-[#0a0a12]">
        {/* Persistent background & global tsParticles context */}
        <StarfieldProvider>
          {children}
        </StarfieldProvider>
      </body>
    </html>
  );
}